language: python
sudo: required
dist: xenial
before_install: "sudo rm -f /etc/boto.cfg"
install: "pip install -r requirements.txt"
matrix:
  include:
    - python: "3.6"
      env: TEST_CMD="make test"
    - python: "3.6"
      env: TEST_CMD="make lint"
    - python: "3.7"
      env: TEST_CMD="make test"
    - python: "3.7"
      env: TEST_CMD="make lint"
script: $TEST_CMD
after_success:
  - codecov